spring:
 datasource:
  url: jdbc:mysql://localhost:3306/mylibrary?useSSL=false
  driverClassName: com.mysql.jdbc.Driver
  username: roxana
  password: '014815'
 jpa:
  database-platform: org.hibernate.dialect.MySQL5Dialect
  show-sql: true
  hibernate:
   ddl-auto: create