spring:
 datasource:
  url: jdbc:mysql://localhost:3306/myLibrary?createDatabaseIfNotExist=true&useSSL=false
  driverClassName: com.mysql.jdbc.Driver
  username: root
  password: koleva01
 jpa:
  database-platform: org.hibernate.dialect.MySQL5Dialect
  show-sql: true
  hibernate:
   ddl-auto: create