package com.kaufland.myLibrary.domain;

public enum Genre {
        ACTION, CONTEMPORARY, CRIME,CHILDBOOKS, FANTASY, FICTION, HISTORYCAL, HORROR, MEMORY, MYSTERY, ROMANCE, SCIENCE, SCIENCE_FICTION, THRILLER, YOUNG_ADULT;
}
