package com.kaufland.myLibrary.domain;

public enum Nationality {
   AMERICAN, ARGENTINIAN, AUSTRALIAN, AUSTRIAN, BRITON, BULGARIAN, CANADIAN, ENGLISHMAN, FRENCHMAN, GERMAN, ITALIAN, PORTUGUESE, RUSSIAN;
}
